- name: Step 1
  hosts: masters
  become: true
  tasks:
    - name: Get join command
      ansible.builtin.command: kubeadm token create --print-join-command
      register: join_command_raw
      changed_when: false

    - name: Set fact join command
      ansible.builtin.set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- name: Step 2
  hosts: workers
  become: true
  tasks:
    - name: Wait for API Server Availability
      ansible.builtin.wait_for:
        host: 192.168.56.11
        port: 6443

    - name: Join Worker Nodes
      ansible.builtin.command: "{{ hostvars[groups['masters'][0]]['join_command'] }}"
      changed_when: false
